public partial class ConScript
{
    private void RegisterActors()
    {

        traps.RegisterActor(A_SPACESHUTTLE, SPACESHUTTLE, enemy, TOUGH);
        traps.RegisterActor(A_SATELLITE, SATELLITE, enemy, TOUGH);
        traps.RegisterActor(A_SHARK, SHARK, enemy, SHARKSTRENGTH, ASHARKCRUZING, SHARKVELS, randomangle, geth);
        traps.RegisterActor(A_BLIMP, BLIMP, enemy, 1);
        traps.RegisterActor(A_RUBBERCAN, RUBBERCAN, enemy, WEAK);
        traps.RegisterActor(A_DUKEBURGER, DUKEBURGER, notenemy, PIRATEGALSTRENGTH, ABURGERROTS);
        traps.RegisterActor(A_MOP, MOP, notenemy, WEAK);
        traps.RegisterActor(A_BROOM, BROOM, notenemy, WEAK);
        traps.RegisterActor(A_WETFLOOR, WETFLOOR, notenemy, WEAK);
        traps.RegisterActor(A_DESKLAMP, DESKLAMP, notenemy, WEAK);
        traps.RegisterActor(A_HATRACK, HATRACK, notenemy, WEAK);
        traps.RegisterActor(A_GUNPOWDERBARREL, GUNPOWDERBARREL, notenemy, TOUGH);
        traps.RegisterActor(A_COFFEEMACHINE, COFFEEMACHINE, notenemy, WEAK);
        traps.RegisterActor(A_TEDDYBEAR, TEDDYBEAR, notenemy, WEAK);
        traps.RegisterActor(A_TOPSECRET, TOPSECRET, notenemy, WEAK);
        traps.RegisterActor(A_ROBOTMOUSE, ROBOTMOUSE, notenemy, ROBOTMOUSESTRENGTH);
        traps.RegisterActor(A_MAN, MAN, notenemy, PIRATEGALSTRENGTH);
        traps.RegisterActor(A_MAN2, MAN2, notenemy, PIRATEGALSTRENGTH);
        traps.RegisterActor(A_WOMAN, WOMAN, notenemy, PIRATEGALSTRENGTH);
        traps.RegisterActor(A_PIRATE1A, PIRATE1A, notenemy, PIRATEGALSTRENGTH);
        traps.RegisterActor(A_PIRATE2A, PIRATE2A, notenemy, PIRATEGALSTRENGTH);
        traps.RegisterActor(A_PIRATE3A, PIRATE3A, notenemy, PIRATEGALSTRENGTH);
        traps.RegisterActor(A_PIRATE4A, PIRATE4A, notenemy, PIRATEGALSTRENGTH);
        traps.RegisterActor(A_PIRATE5A, PIRATE5A, notenemy, PIRATEGALSTRENGTH);
        traps.RegisterActor(A_PIRATE6A, PIRATE6A, notenemy, PIRATEGALSTRENGTH);
        traps.RegisterActor(A_ROBOTPIRATE, ROBOTPIRATE, notenemy, PIRATEGALSTRENGTH);
        traps.RegisterActor(A_PIRATEHALF, PIRATEHALF, notenemy, TOUGH);
        traps.RegisterActor(A_CHESTOFGOLD, CHESTOFGOLD, notenemy, WEAK);
        traps.RegisterActor(A_ROBOTDOG, ROBOTDOG, notenemy, PIRATEGALSTRENGTH);
        traps.RegisterActor(A_ROBOTDOG2, ROBOTDOG2, notenemy, TOUGH);
        traps.RegisterActor(A_PLEASEWAIT, PLEASEWAIT, notenemy);
        traps.RegisterActor(A_FOODOBJECT1, FOODOBJECT1, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT2, FOODOBJECT2, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT3, FOODOBJECT3, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT4, FOODOBJECT4, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT5, FOODOBJECT5, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT6, FOODOBJECT6, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT7, FOODOBJECT7, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT8, FOODOBJECT8, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT9, FOODOBJECT9, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT10, FOODOBJECT10, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT11, FOODOBJECT11, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT12, FOODOBJECT12, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT13, FOODOBJECT13, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT14, FOODOBJECT14, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT15, FOODOBJECT15, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT16, FOODOBJECT16, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT17, FOODOBJECT17, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT18, FOODOBJECT18, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT19, FOODOBJECT19, notenemy, WEAK);
        traps.RegisterActor(A_FOODOBJECT20, FOODOBJECT20, notenemy, WEAK);
        traps.RegisterActor(A_JOLLYMEAL, JOLLYMEAL, notenemy, WEAK);
        traps.RegisterActor(A_GUMBALLMACHINE, GUMBALLMACHINE, notenemy, WEAK);
        traps.RegisterActor(A_GUMBALLMACHINEBROKE, GUMBALLMACHINEBROKE, notenemy, WEAK);
        traps.RegisterActor(A_POLICELIGHTPOLE, POLICELIGHTPOLE, notenemy, TOUGH);
        traps.RegisterActor(A_CLOCK, CLOCK, notenemy, WEAK);
        traps.RegisterActor(A_MAILBAG, MAILBAG, notenemy, WEAK);
        traps.RegisterActor(A_FEATHEREDCHICKEN, FEATHEREDCHICKEN, notenemy, WEAK);
        traps.RegisterActor(A_SKINNEDCHICKEN, SKINNEDCHICKEN, notenemy, WEAK);
        traps.RegisterActor(A_HEADLAMP, HEADLAMP, notenemy, WEAK);
        traps.RegisterActor(A_DOLPHIN1, DOLPHIN1, notenemy, DOLPHINSTRENGTH);
        traps.RegisterActor(A_DOLPHIN2, DOLPHIN2, notenemy, DOLPHINSTRENGTH);
        traps.RegisterActor(A_SNAKEP, SNAKEP, notenemy, MEDIUMSTRENGTH);
        traps.RegisterActor(A_DONUTS, DONUTS, notenemy, WEAK);
        traps.RegisterActor(A_GAVALS, GAVALS, notenemy, WEAK);
        traps.RegisterActor(A_GAVALS2, GAVALS2, notenemy, WEAK);
        traps.RegisterActor(A_CUPS, CUPS, notenemy, WEAK);
        traps.RegisterActor(A_DONUTS2, DONUTS2, notenemy, WEAK);
        traps.RegisterActor(A_FLOORBASKET, FLOORBASKET, notenemy, WEAK);
        traps.RegisterActor(A_METER, METER, notenemy, WEAK);
        traps.RegisterActor(A_DESKPHONE, DESKPHONE, notenemy, WEAK);
        traps.RegisterActor(A_MACE, MACE, notenemy, WEAK);
        traps.RegisterActor(A_SHOPPINGCART, SHOPPINGCART, notenemy, WEAK);
        traps.RegisterActor(A_COFFEEMUG, COFFEEMUG, notenemy, WEAK);
        traps.RegisterActor(A_EXPLODINGBARREL, EXPLODINGBARREL, enemy, 26);
        traps.RegisterActor(A_BURNING, BURNING, enemy, WEAK, BURNING_FLAME);
        traps.RegisterActor(A_BURNING2, BURNING2, enemy, WEAK, BURNING_FLAME);
        traps.RegisterActor(A_TOILETWATER, TOILETWATER, enemy, 0, TOILETWATERFRAMES);
        traps.RegisterActor(A_HORSEONSIDE, HORSEONSIDE, enemy, WEAKEST);
        traps.RegisterActor(A_WOODENHORSE, WOODENHORSE, enemy, WEAK, WOODENHORSEFRAME);
        traps.RegisterActor(A_STEAM, STEAM, enemy, 0, STEAMFRAMES);
        traps.RegisterActor(A_CEILINGSTEAM, CEILINGSTEAM, enemy, 0, STEAMFRAMES);
        traps.RegisterActor(A_WATERBUBBLEMAKER, WATERBUBBLEMAKER, enemy, 0, null/*, randomangle*/); // jmarshall: random angle
        traps.RegisterActor(A_WATERBUBBLE, WATERBUBBLE, enemy, 0, BUBBLE, BUBMOVE/*, getv, geth, randomangle*/); // jmarshall
        traps.RegisterActor(A_SMALLSMOKE, SMALLSMOKE, enemy, 0, SMOKEFRAMES);
        traps.RegisterActor(A_NUKEBARRELDENTED, NUKEBARRELDENTED, enemy, WEAK);
        traps.RegisterActor(A_NUKEBARRELLEAKED, NUKEBARRELLEAKED, enemy, WEAK);
        traps.RegisterActor(A_NUKEBARREL, NUKEBARREL, enemy, MEDIUMSTRENGTH);
        traps.RegisterActor(A_FIREBARREL, FIREBARREL, enemy);
        traps.RegisterActor(A_FIREVASE, FIREVASE, enemy);
        traps.RegisterActor(A_SHRINKEREXPLOSION, SHRINKEREXPLOSION, enemy, 0, SHRINKERFRAMES);
        traps.RegisterActor(A_EXPLOSION2, EXPLOSION2, enemy, 1, EXPLOSION_FRAMES);
        traps.RegisterActor(A_EXPLOSION2BOT, EXPLOSION2BOT, enemy, 1, EXPLOSION_FRAMES);
        traps.RegisterActor(A_FLOORFLAME, FLOORFLAME, enemy, 0, FFLAME_FR);
        traps.RegisterActor(A_ROTATEGUN, ROTATEGUN, enemy, ROTTURRETSTRENGTH);
        traps.RegisterActor(A_FORCERIPPLE, FORCERIPPLE, enemy, 0, RIP_F);
        traps.RegisterActor(A_TRANSPORTERSTAR, TRANSPORTERSTAR, enemy, 0, TRANSFOWARD);
        traps.RegisterActor(A_TRANSPORTERBEAM, TRANSPORTERBEAM, enemy, 0, BEAMFOWARD);
        traps.RegisterActor(A_STEROIDS, STEROIDS, enemy);
        traps.RegisterActor(A_BOOTS, BOOTS, enemy);
        traps.RegisterActor(A_HEATSENSOR, HEATSENSOR, enemy);
        traps.RegisterActor(A_SHIELD, SHIELD, enemy);
        traps.RegisterActor(A_AIRTANK, AIRTANK, enemy);
        traps.RegisterActor(A_HOLODUKE, HOLODUKE, enemy, 0, HOLODUKE_FRAMES);
        traps.RegisterActor(A_JETPACK, JETPACK, enemy);
        traps.RegisterActor(A_ACCESSCARD, ACCESSCARD, enemy);
        traps.RegisterActor(A_AMMO, AMMO, enemy);
        traps.RegisterActor(A_FREEZEAMMO, FREEZEAMMO, enemy);
        traps.RegisterActor(A_SHOTGUNAMMO, SHOTGUNAMMO, enemy);
        traps.RegisterActor(A_AMMOLOTS, AMMOLOTS, enemy);
        traps.RegisterActor(A_CRYSTALAMMO, CRYSTALAMMO, enemy);
        traps.RegisterActor(A_GROWAMMO, GROWAMMO, enemy);
        traps.RegisterActor(A_BATTERYAMMO, BATTERYAMMO, enemy);
        traps.RegisterActor(A_DEVISTATORAMMO, DEVISTATORAMMO, enemy);
        traps.RegisterActor(A_RPGAMMO, RPGAMMO, enemy);
        traps.RegisterActor(A_HBOMBAMMO, HBOMBAMMO, enemy);
        traps.RegisterActor(A_RPGSPRITE, RPGSPRITE, enemy);
        traps.RegisterActor(A_SHOTGUNSPRITE, SHOTGUNSPRITE, enemy);
        traps.RegisterActor(A_SIXPAK, SIXPAK, enemy);
        traps.RegisterActor(A_COLA, COLA, enemy);
        traps.RegisterActor(A_ATOMICHEALTH, ATOMICHEALTH, enemy);
        traps.RegisterActor(A_FIRSTAID, FIRSTAID, enemy);
        traps.RegisterActor(A_FIRSTGUNSPRITE, FIRSTGUNSPRITE, enemy);
        traps.RegisterActor(A_TRIPBOMBSPRITE, TRIPBOMBSPRITE, enemy);
        traps.RegisterActor(A_CHAINGUNSPRITE, CHAINGUNSPRITE, enemy);
        traps.RegisterActor(A_SHRINKERSPRITE, SHRINKERSPRITE, enemy);
        traps.RegisterActor(A_FREEZESPRITE, FREEZESPRITE, enemy);
        traps.RegisterActor(A_DEVISTATORSPRITE, DEVISTATORSPRITE, enemy);
        traps.RegisterActor(A_FIRE, FIRE, notenemy, WEAK, null, FIREVELS);
        traps.RegisterActor(A_FIRE2, FIRE2, notenemy, WEAK, null, FIREVELS);
        traps.RegisterActor(A_FECES, FECES, enemy);
        traps.RegisterActor(A_FEM1, FEM1, enemy, TOUGH, FEMANIMATE);
        traps.RegisterActor(A_FEM2, FEM2, enemy, TOUGH, FEMANIMATE);
        traps.RegisterActor(A_FEM3, FEM3, enemy, TOUGH, FEMANIMATE);
        traps.RegisterActor(A_FEM4, FEM4, enemy, TOUGH, FEMANIMATE);
        traps.RegisterActor(A_FEM5, FEM5, enemy, TOUGH, FEMANIMATE);
        traps.RegisterActor(A_FEM6, FEM6, enemy, TOUGH, FEMANIMATE);
        traps.RegisterActor(A_FEM7, FEM7, enemy, TOUGH, FEMANIMATE);
        traps.RegisterActor(A_FEM8, FEM8, enemy, TOUGH, FEMANIMATE);
        traps.RegisterActor(A_FEM9, FEM9, enemy, TOUGH, FEMANIMATE);
        traps.RegisterActor(A_FEM10, FEM10, enemy, TOUGH, FEMANIMATESLOW);
        traps.RegisterActor(A_TOUGHGAL, TOUGHGAL, enemy, MANWOMANSTRENGTH, TOUGHGALANIM);
        traps.RegisterActor(A_NAKED1, NAKED1, enemy, TOUGH, FEMANIMATE);
        traps.RegisterActor(A_PODFEM1, PODFEM1, enemy, TOUGH, FEMANIMATE);
        traps.RegisterActor(A_BLOODYPOLE, BLOODYPOLE, enemy, TOUGH);
        traps.RegisterActor(A_STATUEFLASH, STATUEFLASH, enemy);
        traps.RegisterActor(A_STATUE, STATUE, enemy);
        traps.RegisterActor(A_MIKE, MIKE, enemy);
        traps.RegisterActor(A_BLOOD, BLOOD, enemy, 0, BLOODFRAMES);
        traps.RegisterActor(A_EGG, EGG, enemy, TOUGH);
        traps.RegisterActor(A_KNEE, KNEE, enemy, KNEE_WEAPON_STRENGTH);
        traps.RegisterActor(A_SPIT, SPIT, enemy, SPIT_WEAPON_STRENGTH);
        traps.RegisterActor(A_CHAINGUN, CHAINGUN, enemy, CHAINGUN_WEAPON_STRENGTH);
        traps.RegisterActor(A_SHOTGUN, SHOTGUN, enemy, SHOTGUN_WEAPON_STRENGTH);
        traps.RegisterActor(A_FIRELASER, FIRELASER, enemy, FIRELASER_WEAPON_STRENGTH);
        traps.RegisterActor(A_HEAVYHBOMB, HEAVYHBOMB, enemy, HANDBOMB_WEAPON_STRENGTH);
        traps.RegisterActor(A_BOUNCEMINE, BOUNCEMINE, enemy, BOUNCEMINE_WEAPON_STRENGTH);
        traps.RegisterActor(A_MORTER, MORTER, enemy, MORTER_WEAPON_STRENGTH);
        traps.RegisterActor(A_SHRINKSPARK, SHRINKSPARK, enemy, SHRINKER_WEAPON_STRENGTH);
        traps.RegisterActor(A_GROWSPARK, GROWSPARK, enemy, GROWSPARK_WEAPON_STRENGTH);
        traps.RegisterActor(A_RPG, RPG, enemy, RPG_WEAPON_STRENGTH);
        traps.RegisterActor(A_FREEZEBLAST, FREEZEBLAST, enemy, FREEZETHROWER_WEAPON_STRENGTH);
        traps.RegisterActor(A_DEVISTATORBLAST, DEVISTATORBLAST, enemy, FREEZETHROWER_WEAPON_STRENGTH);
        traps.RegisterActor(A_COOLEXPLOSION1, COOLEXPLOSION1, enemy, COOL_EXPLOSION_STRENGTH);
        traps.RegisterActor(A_TRIPBOMB, TRIPBOMB, enemy, TRIPBOMB_STRENGTH);
        traps.RegisterActor(A_SHOTSPARK1, SHOTSPARK1, enemy, PISTOL_WEAPON_STRENGTH, WEAP2FRAMES);
        traps.RegisterActor(A_DUKELYINGDEAD, DUKELYINGDEAD, enemy, 0, PLYINGFRAMES);
        traps.RegisterActor(A_APLAYER, APLAYER, enemy, MAXPLAYERHEALTH, PSTAND, null, 0);
        traps.RegisterActor(A_ORGANTIC, ORGANTIC, enemy, TURRETSTRENGTH);
        traps.RegisterActor(A_LIZTROOPJETPACK, LIZTROOPJETPACK, enemy, TROOPSTRENGTH);
        traps.RegisterActor(A_LIZTROOPDUCKING, LIZTROOPDUCKING, enemy, TROOPSTRENGTH);
        traps.RegisterActor(A_LIZTROOPSHOOT, LIZTROOPSHOOT, enemy, TROOPSTRENGTH, ATROOPSTAND);
        traps.RegisterActor(A_LIZTROOPSTAYPUT, LIZTROOPSTAYPUT, enemy, TROOPSTRENGTH, ATROOPSTAYSTAND);
        traps.RegisterActor(A_LIZTROOPRUNNING, LIZTROOPRUNNING, enemy, TROOPSTRENGTH, ATROOPSTAND);
        traps.RegisterActor(A_LIZTROOPONTOILET, LIZTROOPONTOILET, enemy, TROOPSTRENGTH);
        traps.RegisterActor(A_LIZTROOPJUSTSIT, LIZTROOPJUSTSIT, enemy, TROOPSTRENGTH);
        traps.RegisterActor(A_LIZTROOP, LIZTROOP, enemy, TROOPSTRENGTH, ATROOPSTAND);
        traps.RegisterActor(A_LIZMANSTAYPUT, LIZMANSTAYPUT, enemy, LIZSTRENGTH);
        traps.RegisterActor(A_LIZMANSPITTING, LIZMANSPITTING, enemy, LIZSTRENGTH);
        traps.RegisterActor(A_LIZMANJUMP, LIZMANJUMP, enemy, LIZSTRENGTH);
        traps.RegisterActor(A_LIZMAN, LIZMAN, enemy, LIZSTRENGTH);
        traps.RegisterActor(A_DRONE, DRONE, enemy, DRONESTRENGTH);
        traps.RegisterActor(A_OCTABRAINSTAYPUT, OCTABRAINSTAYPUT, enemy, OCTASTRENGTH);
        traps.RegisterActor(A_OCTABRAIN, OCTABRAIN, enemy, OCTASTRENGTH);
        traps.RegisterActor(A_PIGCOPDIVE, PIGCOPDIVE, enemy, PIGCOPSTRENGTH);
        traps.RegisterActor(A_PIGCOPSTAYPUT, PIGCOPSTAYPUT, enemy, PIGCOPSTRENGTH);
        traps.RegisterActor(A_PIGCOP, PIGCOP, enemy, PIGCOPSTRENGTH, APIGSTAND);
        traps.RegisterActor(A_BOSS1STAYPUT, BOSS1STAYPUT, enemy, BOSS1STRENGTH);
        traps.RegisterActor(A_BOSS1, BOSS1, enemy, BOSS1STRENGTH);
        traps.RegisterActor(A_BOSS2, BOSS2, enemy, BOSS2STRENGTH);
        traps.RegisterActor(A_BOSS3, BOSS3, enemy, BOSS3STRENGTH);
        traps.RegisterActor(A_COMMANDERSTAYPUT, COMMANDERSTAYPUT, enemy, COMMANDERSTRENGTH);
        traps.RegisterActor(A_COMMANDER, COMMANDER, enemy, COMMANDERSTRENGTH);
        traps.RegisterActor(A_CANNONBALL, CANNONBALL, notenemy, CANNONBALLSTRENGTH);
        traps.RegisterActor(A_CANNONBALLS, CANNONBALLS, notenemy, CANNONBALLSSTRENGTH);
        traps.RegisterActor(A_CANNON, CANNON, enemy, CANNONSTRENGTH);
        traps.RegisterActor(A_HOTMEAT, HOTMEAT, notenemy, TOUGH);
        traps.RegisterActor(A_SPEAKER, SPEAKER, notenemy);
        traps.RegisterActor(A_LAVABUBBLE, LAVABUBBLE, notenemy);
        traps.RegisterActor(A_TANK, TANK, enemy, TANKSTRENGTH);
        traps.RegisterActor(A_BOSS4STAYPUT, BOSS4STAYPUT, enemy, BOSS4STRENGTH);
        traps.RegisterActor(A_BOSS4, BOSS4, enemy, BOSS4STRENGTH);
        traps.RegisterActor(A_NEWBEASTHANG, NEWBEASTHANG, enemy, NEWBEASTSTRENGTH);
        traps.RegisterActor(A_NEWBEASTHANGDEAD, NEWBEASTHANGDEAD, enemy, TOUGH);
        traps.RegisterActor(A_NEWBEASTSTAYPUT, NEWBEASTSTAYPUT, enemystayput, NEWBEASTSTRENGTH);
        traps.RegisterActor(A_NEWBEASTJUMP, NEWBEASTJUMP, enemy, NEWBEASTSTRENGTH);
        traps.RegisterActor(A_NEWBEAST, NEWBEAST, enemy, NEWBEASTSTRENGTH);
    }
}